### ISSUE TITLE
Build failure on Windows and macOS

### ISSUE THREAD

**Issue by nbigaouette** [rust-analyzer/rust-analyzer#1939]
While Travis builds pass, latest HEAD (31f22d85491d9e7eaadf5fd4f9754c83fc0f3ea6) fails on both macOS and Windows.

Here's the error:

```
> git checkout 31f22d85491d9e7eaadf5fd4f9754c83fc0f3ea6
> cargo install-ra
[...]
error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
   --> crates/ra_hir/src/ty/infer.rs:695:22
    |
695 |                     .collect();
    |                      ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Ite
m=ty::Ty>`
    |
    = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
  --> crates/ra_hir/src/ty/infer/unify.rs:79:83
   |
79 |             trait_ref.substs.iter().map(|ty| self.do_canonicalize_ty(ty.clone())).collect();
   |                                                                                   ^^^^^^^ a collection of type `std::sync::
Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
   |
   = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
  --> crates/ra_hir/src/ty/infer/unify.rs:92:91
   |
92 |             projection_ty.parameters.iter().map(|ty| self.do_canonicalize_ty(ty.clone())).collect();
   |                                                                                           ^^^^^^^ a collection of type `std
::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
   |
   = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
   --> crates/ra_hir/src/ty/infer/unify.rs:151:82
    |
151 |         let new_vars = Substs((0..solution.num_vars).map(|_| ctx.new_type_var()).collect());
    |                                                                                  ^^^^^^^ a collection of type `std::sync::
Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
    |
    = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
error: failed to compile `ra_lsp_server v0.1.0 (/Users/nbigaouette/rust-analyzer/crates/ra_lsp_server)`, intermediate
 artifacts can be found at `/Users/nbigaouette/rust-analyzer/target`

Caused by:
  Could not compile `ra_hir`.

To learn more, run the command again with --verbose.
Error: "`cargo install --path crates/ra_lsp_server --locked --force` exited with exit code: 101"
```

Bisecting right now from c12a713739e30019497ab0f5e7bfa776122bfc6d since it compiled last week.

**Comment by matklad** [comment]
I think you need to update rust version: rust-analyzer requires latest
stable to compile

**Comment by nbigaouette** [comment]
Finished bisection:
```
daaf46177e5dc63e20e5a1ec5692e53cc8f7bc34 is the first bad commit
commit daaf46177e5dc63e20e5a1ec5692e53cc8f7bc34
Author: Florian Diebold <flodiebold@gmail.com>
Date:   Thu Sep 26 21:37:03 2019 +0200

    Add SubstsBuilder

    + further refactoring.

 crates/ra_hir/src/code_model.rs           |  14 ++-
 crates/ra_hir/src/marks.rs                |   1 -
 crates/ra_hir/src/ty.rs                   | 141 ++++++++++++++++++++++++++++--
 crates/ra_hir/src/ty/autoderef.rs         |  14 +--
 crates/ra_hir/src/ty/infer.rs             |  15 ++--
 crates/ra_hir/src/ty/infer/path.rs        |  10 +--
 crates/ra_hir/src/ty/infer/unify.rs       |  24 ++---
 crates/ra_hir/src/ty/lower.rs             |  20 +++--
 crates/ra_hir/src/ty/method_resolution.rs |  18 ++--
 crates/ra_hir/src/ty/tests.rs             |   1 -
 crates/ra_hir/src/ty/traits/chalk.rs      |  80 ++++-------------
 11 files changed, 212 insertions(+), 126 deletions(-)
```

This is with:
```
rustc -V
rustc 1.37.0 (eae3437df 2019-08-13)
```

Will try latest...

**Comment by nbigaouette** [comment]
Tried 31f22d85491d9e7eaadf5fd4f9754c83fc0f3ea6 with 1.38 and it worked.

Thanks!
