### ISSUE TITLE
Failed to download: fetch$1 is not a function

### ISSUE THREAD

**Issue by kafji** [rust-analyzer/rust-analyzer#6757]
After upgrading to latest nightly (v0.3.409-nightly) my Vscode failed to download the language server binary and shows `Failed to download: fetch$1 is not a function` error popup.

![Screenshot from 2020-12-08 09-42-02_cropped](https://user-images.githubusercontent.com/1842143/101441562-4e8ca700-3911-11eb-8730-2d2ebab75ec4.png)

I've tried the "Update Github Auth Token" and use my personal account token but the error persist.

RA client log:
```
DEBUG [12/8/2020, 9:41:49 AM]: Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly
ERROR [12/8/2020, 9:45:42 AM]: [TypeError: fetch$1 is not a function
	at Object.fetchRelease (/home/asd/.vscode/extensions/matklad.rust-analyzer-0.3.409-nightly/out/src/main.js:17893:28)
	at /home/asd/.vscode/extensions/matklad.rust-analyzer-0.3.409-nightly/out/src/main.js:18130:26
	at downloadWithRetryDialog (/home/asd/.vscode/extensions/matklad.rust-analyzer-0.3.409-nightly/out/src/main.js:18277:26)
	at bootstrapExtension (/home/asd/.vscode/extensions/matklad.rust-analyzer-0.3.409-nightly/out/src/main.js:18129:27)
	at bootstrap (/home/asd/.vscode/extensions/matklad.rust-analyzer-0.3.409-nightly/out/src/main.js:18105:11)
	at async tryActivate (/home/asd/.vscode/extensions/matklad.rust-analyzer-0.3.409-nightly/out/src/main.js:18028:24)
	at async activate (/home/asd/.vscode/extensions/matklad.rust-analyzer-0.3.409-nightly/out/src/main.js:18002:5)
	at async Promise.all (index 0)]
```

_Copied from https://users.rust-lang.org/t/ra-failed-to-download-fetch-1-is-not-a-function/52464._

**Comment by hammypants** [comment]
Also getting this on `nightly`-- it's basically dead in the water atm.

**Comment by kafji** [comment]
This issue is introduced in 31f50446ac782e5ee78429616e91b2a0afc2af24.

Maybe something related to rollup. https://github.com/rust-analyzer/rust-analyzer/blob/dfd0626dbfea6816d38e6f72ce84f567877603e7/editors/code/src/net.ts#L1-L3?

**Comment by kafji** [comment]
```
diff --git a/editors/code/src/net.ts b/editors/code/src/net.ts
index 9ba17b7b5..22cb38552 100644
--- a/editors/code/src/net.ts
+++ b/editors/code/src/net.ts
@@ -1,6 +1,7 @@
 // Replace with `import fetch from "node-fetch"` once this is fixed in rollup:
 // https://github.com/rollup/plugins/issues/491
-const fetch = require("node-fetch") as typeof import("node-fetch")["default"];
+// const fetch = require("node-fetch") as typeof import("node-fetch")["default"];
+import fetch from "node-fetch";
 
 import * as vscode from "vscode";
 import * as stream from "stream";
```

Does fix the issue.

**Comment by kafji** [comment]
Patched.

**Comment by mexus** [comment]
So for today we've got a broken nightly, right? Is it possible to somehow update it before tomorrow?

**Comment by kafji** [comment]
> So for today we've got a broken nightly, right?

I believe so.

> Is it possible to somehow update it before tomorrow?

Yes. You can download the [server binary](https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly) and copy it to the [expected path](https://rust-analyzer.github.io/manual.html#vs-code).

**Comment by mexus** [comment]
Thanks @kafji ! So far re-installing the extension helped, but who knows what happens tomorrow.. it's still 2020 after all..

**Comment by chinoto** [comment]
I was just about to open an issue, but then I decided to check the closed issues, thanks for the fix, @kafji, and how to get the fix to stick, @mexus. (Do I have my comma grammar right?)
